services:
  auth_service:
    build:
      context: ./auth_service
    env_file:
      - ./auth_service/.env
    environment:
      SQLITE_PATH: /app/data/auth.db
    ports:
      - "8000:8000"
    volumes:
      - auth_data:/app/data
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000

  bot_api:
    build:
      context: ./bot_service
    env_file:
      - ./bot_service/.env
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - rabbitmq
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000

  telegram_bot:
    build:
      context: ./bot_service
    env_file:
      - ./bot_service/.env
    depends_on:
      - redis
      - rabbitmq
    command: uv run python -m app.bot.run_bot

  bot_worker:
    build:
      context: ./bot_service
    env_file:
      - ./bot_service/.env
    depends_on:
      - redis
      - rabbitmq
    command: uv run celery -A app.infra.celery_app.celery_app worker --loglevel=info

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  auth_data:
